analyzer:
  errors:
    avoid_print: ignore
    avoid_unnecessary_containers: ignore
    file_names: ignore
    non_constant_identifier_names: ignore 
    override_on_non_overriding_member: ignore
    prefer_const_constructors: ignore 
    prefer_const_literals_to_create_immutables: ignore
    prefer_typing_uninitialized_variables: ignore
    unnecessary_import: ignore
    unused_element: ignore
    unused_import: ignore
    unused_local_variable: ignore
    use_key_in_widget_constructors: ignore 
include: package:flutter_lints/flutter.yaml
